#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="${BASE_DIR:-$PWD}"
DATA_ROOT="${DATA_ROOT:-/root/data/agentcoder_stage5}"
RAW_DIR="${RAW_DIR:-$DATA_ROOT/raw}"
PACKED_DIR="${PACKED_DIR:-$DATA_ROOT/packed_2048}"
TOKENIZER="${TOKENIZER:-$DATA_ROOT/tokenizer.json}"
RUN_DIR="${RUN_DIR:-$BASE_DIR/runs/stage5_raam_agentcoder_100m_stage5_stable}"
CONFIG="${CONFIG:-configs/scratch/raam_agentcoder_100m_stage5_stable.yaml}"
START_CHECKPOINT="${START_CHECKPOINT:-}"
RAAM_MLOPS_PROJECT_PATH="${RAAM_MLOPS_PROJECT_PATH:-}"

# Moderate defaults are meant to grow beyond the tiny gate while still being
# feasible on one RTX 5090. Override these upward when disk and time allow.
MAX_OPEN_SWE="${MAX_OPEN_SWE:-10000}"
MAX_SWE_ZERO="${MAX_SWE_ZERO:-10000}"
MAX_WILDCHAT="${MAX_WILDCHAT:-10000}"
MAX_OASST="${MAX_OASST:-5000}"
STARCODER2_EXTRAS="${STARCODER2_EXTRAS:-documentation=10000 issues=10000 stackoverflow=10000 kaggle=5000}"

STEPS="${STEPS:-5000}"
RESUME_STEPS="${RESUME_STEPS:-5500}"
SAVE_EVERY="${SAVE_EVERY:-0}"
EVAL_EVERY="${EVAL_EVERY:-100}"
EXPORT_CHECKPOINT="${EXPORT_CHECKPOINT:-1}"
KEEP_TRAINING_CHECKPOINTS="${KEEP_TRAINING_CHECKPOINTS:-1}"
BATCH_SIZE="${BATCH_SIZE:-}"
TRAIN_SEQ_LEN="${TRAIN_SEQ_LEN:-}"
GRAD_ACCUMULATION_STEPS="${GRAD_ACCUMULATION_STEPS:-}"
EVAL_BATCHES="${EVAL_BATCHES:-}"
VOCAB_SIZE="${VOCAB_SIZE:-32768}"
SEQ_LEN="${SEQ_LEN:-2048}"
ASSISTANT_LOSS_ONLY="${ASSISTANT_LOSS_ONLY:-0}"
AGENT_RECORDS_ONLY="${AGENT_RECORDS_ONLY:-0}"
SCORE_PLAIN_TEXT_LOSS="${SCORE_PLAIN_TEXT_LOSS:-1}"
MAX_PACK_DOCUMENTS="${MAX_PACK_DOCUMENTS:-0}"
MAX_PACK_DOCUMENT_CHARS="${MAX_PACK_DOCUMENT_CHARS:-0}"
SAVE_BEST="${SAVE_BEST:-}"
EARLY_STOP_PATIENCE_EVALS="${EARLY_STOP_PATIENCE_EVALS:-}"
EARLY_STOP_MIN_DELTA="${EARLY_STOP_MIN_DELTA:-}"
EARLY_STOP_MIN_STEP="${EARLY_STOP_MIN_STEP:-}"
RESTORE_BEST_ON_FINISH="${RESTORE_BEST_ON_FINISH:-}"
VALIDATION_LR_DECAY_PATIENCE_EVALS="${VALIDATION_LR_DECAY_PATIENCE_EVALS:-}"
VALIDATION_LR_DECAY_FACTOR="${VALIDATION_LR_DECAY_FACTOR:-}"
VALIDATION_LR_DECAY_MIN_SCALE="${VALIDATION_LR_DECAY_MIN_SCALE:-}"
VALIDATION_LR_DECAY_MIN_STEP="${VALIDATION_LR_DECAY_MIN_STEP:-}"
USE_BEST_CHECKPOINT_FOR_EVAL="${USE_BEST_CHECKPOINT_FOR_EVAL:-1}"
RUN_QUALITATIVE_INSPECT="${RUN_QUALITATIVE_INSPECT:-0}"
QUALITATIVE_SEEDS="${QUALITATIVE_SEEDS:-17}"

BASE_DIR="$BASE_DIR" \
DATA_ROOT="$DATA_ROOT" \
RAW_DIR="$RAW_DIR" \
PACKED_DIR="$PACKED_DIR" \
TOKENIZER="$TOKENIZER" \
RUN_DIR="$RUN_DIR" \
CONFIG="$CONFIG" \
START_CHECKPOINT="$START_CHECKPOINT" \
RAAM_MLOPS_PROJECT_PATH="$RAAM_MLOPS_PROJECT_PATH" \
MAX_OPEN_SWE="$MAX_OPEN_SWE" \
MAX_SWE_ZERO="$MAX_SWE_ZERO" \
MAX_WILDCHAT="$MAX_WILDCHAT" \
MAX_OASST="$MAX_OASST" \
STARCODER2_EXTRAS="$STARCODER2_EXTRAS" \
STEPS="$STEPS" \
RESUME_STEPS="$RESUME_STEPS" \
SAVE_EVERY="$SAVE_EVERY" \
EVAL_EVERY="$EVAL_EVERY" \
EXPORT_CHECKPOINT="$EXPORT_CHECKPOINT" \
KEEP_TRAINING_CHECKPOINTS="$KEEP_TRAINING_CHECKPOINTS" \
BATCH_SIZE="$BATCH_SIZE" \
TRAIN_SEQ_LEN="$TRAIN_SEQ_LEN" \
GRAD_ACCUMULATION_STEPS="$GRAD_ACCUMULATION_STEPS" \
EVAL_BATCHES="$EVAL_BATCHES" \
VOCAB_SIZE="$VOCAB_SIZE" \
SEQ_LEN="$SEQ_LEN" \
ASSISTANT_LOSS_ONLY="$ASSISTANT_LOSS_ONLY" \
AGENT_RECORDS_ONLY="$AGENT_RECORDS_ONLY" \
SCORE_PLAIN_TEXT_LOSS="$SCORE_PLAIN_TEXT_LOSS" \
MAX_PACK_DOCUMENTS="$MAX_PACK_DOCUMENTS" \
MAX_PACK_DOCUMENT_CHARS="$MAX_PACK_DOCUMENT_CHARS" \
SAVE_BEST="$SAVE_BEST" \
EARLY_STOP_PATIENCE_EVALS="$EARLY_STOP_PATIENCE_EVALS" \
EARLY_STOP_MIN_DELTA="$EARLY_STOP_MIN_DELTA" \
EARLY_STOP_MIN_STEP="$EARLY_STOP_MIN_STEP" \
RESTORE_BEST_ON_FINISH="$RESTORE_BEST_ON_FINISH" \
VALIDATION_LR_DECAY_PATIENCE_EVALS="$VALIDATION_LR_DECAY_PATIENCE_EVALS" \
VALIDATION_LR_DECAY_FACTOR="$VALIDATION_LR_DECAY_FACTOR" \
VALIDATION_LR_DECAY_MIN_SCALE="$VALIDATION_LR_DECAY_MIN_SCALE" \
VALIDATION_LR_DECAY_MIN_STEP="$VALIDATION_LR_DECAY_MIN_STEP" \
USE_BEST_CHECKPOINT_FOR_EVAL="$USE_BEST_CHECKPOINT_FOR_EVAL" \
RUN_QUALITATIVE_INSPECT="$RUN_QUALITATIVE_INSPECT" \
QUALITATIVE_SEEDS="$QUALITATIVE_SEEDS" \
bash scripts/vast_train_50m.sh
